### ISSUE TITLE
Verify() returns invalid ethereal address

### ISSUE THREAD

**Issue by markusbug** [bytesbay/web3-token#1]
Hi!
The verify() function returns an uppercase version of the Ethereum address, but this uppercase version is not a valid address anymore. 
Is there a way to fix this, I would love to help 👍

**Comment by markusbug** [comment]
I already created a pull-request with the fix

**Comment by bytesbay** [comment]
#2 

Changed to toLowerCase() as it still keep address valid for web3 isAddress() method

**Comment by markusbug** [comment]
Thanks 👍
