### ISSUE TITLE
Signature body - prepend a message?

### ISSUE THREAD

**Issue by JohnRSim** [bytesbay/web3-token#10]
Is it possible to prepend a custom message similar to OpenSea?
![image](https://user-images.githubusercontent.com/364208/141297387-fcca641a-ceb4-42ee-a555-c1a4694bf005.png)

I know you can append a message but it would be nice to add a custom message first informing the user what they are signing..

**Comment by deepspacebsc-test** [comment]
I strongly agree this would be a useful feature. The OpenSea message is very educational and something similar would be wonderful.

**Comment by john--** [comment]
Completely agree. The OpenSea like informational message is very educational to the user.

**Comment by JohnRSim** [comment]
At the moment I'm appending the key "Welcome to": " opensea copy text with nonce and wallet address generated"

It's ok but the expiry and token info is prepended above.

**Comment by john--** [comment]
Ah, yeah. I'm actually doing something similar. Even if just being able to re-order the JSON properties was possible, I think it would be useful.

**Comment by john--** [comment]
@bytesbay any thoughts? :)

**Comment by bytesbay** [comment]
@john-- Hey !
sorry for delay , this weekend ill do a large update, ill think is it possible to include this functionality.

**Comment by JohnRSim** [comment]
Looking forward to the update! :)

**Comment by john--** [comment]
Also very interested in the updates here :)

**Comment by john--** [comment]
@bytesbay any luck?

**Comment by bytesbay** [comment]
@john-- Yep, added `statement` option in 2.0 version

**Comment by deepspacebsc-dev** [comment]
Thank you btw. Finally getting around to trying this out today.
