### ISSUE TITLE
How does this library relate to EIP4361, if at all?

### ISSUE THREAD

**Issue by nglglhtr** [bytesbay/web3-token#12]
The [EIP4361](https://github.com/ethereum/EIPs/blob/9a9c5d0abdaf5ce5c5dd6dc88c6d8db1b130e95b/EIPS/eip-4361.md#specification) spec pretty much standardises what this library is somewhat doing. Any plans to make some super tiny changes to be in exact accordance to the spec?

**Comment by bytesbay** [comment]
@nglglhtr Done.

**Comment by nglglhtr** [comment]
You're amazing. thank you.
