### ISSUE TITLE
Expiration fields not match between sign and verify function.

### ISSUE THREAD

**Issue by AtelyPham** [bytesbay/web3-token#17]
The `expiration` fields in the `sign` function is `expiration-time`, but in the `verify` function, you are checking the `expiration-date` field.

Link code:

* [The `sign` function](https://github.com/bytesbay/web3-token/blob/main/src/lib/sign/sign.js#L134)
* [The `verify` function](https://github.com/bytesbay/web3-token/blob/main/src/lib/verify/verify.js#L79)

**Comment by bytesbay** [comment]
That's because of a body parser. But agree that it's not good

**Comment by AtelyPham** [comment]
But it didn't work for the expired token, the error line below cannot reach.

https://github.com/bytesbay/web3-token/blob/main/src/lib/verify/verify.js#L80
