### ISSUE TITLE
Why do you await verify?

### ISSUE THREAD

**Issue by Drarig29** [bytesbay/web3-token#27]
https://github.com/bytesbay/web3-token/blob/a77579931a606f06239b9f06021a8b587f749cd9/src/lib/verify/verify.js#L67

The `verify()` function isn't a promise but you are using `await` with it everywhere. Is it a mistake or to be future-proof? Or to be consistent with `await sign()`?

Because of that I get a warning:

![image](https://user-images.githubusercontent.com/9317502/151353050-cb82b2e8-e69b-49c4-92fe-bef2194ab115.png)

> 'await' has no effect on the type of this expression.

**Comment by bytesbay** [comment]
mistake
