### ISSUE TITLE
Is there any way to make this smaller?

### ISSUE THREAD

**Issue by GibsDev** [bytesbay/web3-token#29]
This adds quite a lot of size to a webpack bundle.

webpack production run results:
![image](https://user-images.githubusercontent.com/5456226/153779948-b6fbb36d-69f3-4aef-a976-d912a97b967b.png)

Any suggestions?

**Comment by bytesbay** [comment]
Reduced the size more than 70% in the latest patch

**Comment by yektas** [comment]
> Reduced the size more than 70% in the latest patch

![image](https://user-images.githubusercontent.com/9054528/174265345-fc267d57-31b6-4362-ae3b-46c0dab27f49.png)

It is still quite a big bundle size 172 KB gzipped 🤔
