### ISSUE TITLE
Renew expired token without metamask - aka JWT refresh token

### ISSUE THREAD

**Issue by iangregsondev** [bytesbay/web3-token#32]
Hi,

I am trying to use this to replace a JWT flow.

i was wondering what options we have to automatically refresh a token using some kind of refresh token ?

so we can safely expire these tokens BUT we can re-create them without user interaction..

This is pretty much a similar flow to JWT with refresh tokens.

Has anybody figured this out yet ?

Or maybe its not needed ?

Thanks in advance

**Comment by 7flash** [comment]
My application requires user to sign only once.. then his signature is verified and saved in the table associated with account id.. next request user provides same signature.. and account name is found by simple search of signature in the table.. even if its expired its still valid.. its not being verified again

**Comment by bytesbay** [comment]
Wallets have to implement this feature (something like renewable sign), it's not possible from this module's side.
