### ISSUE TITLE
Time always 1days

### ISSUE THREAD

**Issue by rharkor** [bytesbay/web3-token#44]
My code look like this : 
```js
const localToken = await web3Token.sign(
  (msg) => signer.signMessage(msg, account),
  {
    statement: rawMessage,
    expire_in: "1m",
  }
);
```
I try many things for the expire_in params but every time the message saiys that the token expire in 1 day

**Comment by bytesbay** [comment]
There's a typo in docs, fixed already 
You need to use `expires_at` instead of `expire_at`
