### ISSUE TITLE
Property 'domain' of type 'string | undefined' is not assignable to 'string' index type 'string | string[]

### ISSUE THREAD

**Issue by alvaro-7x** [bytesbay/web3-token#45]
Hi, I get the errors 

Property 'domain' of type 'string | undefined' is not assignable to 'string' index type 'string | string[]'
Property 'statement' of type 'string | undefined' is not assignable to 'string' index type 'string | string[]'

in Angular 13 when I use 

`const token = await sign( (msg) => web3.eth.personal.sign(msg, address,""), '1d');`

 now it would be advisable to add `undefined` in the VerifyBody interface of the web3-token.d.ts file in line 15 ?

https://github.com/bytesbay/web3-token/blob/7d26edba607ee0256cce8820785120e686fdc68d/dist/web3-token.d.ts#L15-L18

Result:

`interface VerifyBody extends Record<string, string | string[] | undefined> { `

**Comment by bytesbay** [comment]
Fixed in the latest version

**Comment by alvaro-7x** [comment]
ok, thanks
________________________________
De: Miroslaw Shpak ***@***.***>
Enviado: domingo, 4 de septiembre de 2022 10:39
Para: bytesbay/web3-token ***@***.***>
Cc: Alvaro ***@***.***>; Author ***@***.***>
Asunto: Re: [bytesbay/web3-token] Property 'domain' of type 'string | undefined' is not assignable to 'string' index type 'string | string[] (Issue #45)


Fixed in the latest version
