### ISSUE TITLE
Feature request: Export decrypt function

### ISSUE THREAD

**Issue by aleciten** [bytesbay/web3-token#50]
Would it be possible to export the `decrypt` function?

I'd like to be able to decrypt the token even when verification fails.

If this sounds ok to you then I can provide a PR.

Thanks!

**Comment by bytesbay** [comment]
Hey ! Yep , sounds good

**Comment by bytesbay** [comment]
Any updates with this? I have some free time now
@aleciten

**Comment by aleciten** [comment]
Hey! sorry, I haven't had the time just yet, but still plan on doing it..

If you mean you have time to do it, then by all means :)
