### ISSUE TITLE
Cross origin token usage attack?

### ISSUE THREAD

**Issue by kaaboaye** [bytesbay/web3-token#8]
Let's assume that there are two websites using `web3-token`:
 - `website1` which is under my control 
 - `website2` which is under my competitors control.

What stops me from performing the following scenario?

1.  A `user` logs into my `website1` and sends it into my server.
2. My server makes a request to `website2` using the valid `user`'s token created for my `website1`.
3. Since I now have access to the `website2` as the `user` I can steal confidential data.
4. `user` have no way of knowing about this attack unless `website2` sends some notifications about  for example new ip address being used.
5. `website2` also has no way of knowing about this attack since the token is freshly signed valid.

**Comment by bytesbay** [comment]
Thanks for your comment. Im currently preparing update to fit [this](https://github.com/ethereum/EIPs/blob/27b5497268bab4449cbe815ae9812388005d763b/EIPS/eip-4361.md) standard. 

Will add `domain` option which will fix this issue. Meanwhile, you can add a custom `domain` field with your domain while signing a token and then check on server-side if there's a valid `domain` in token's body.

**Comment by kaaboaye** [comment]
What will stop me from putting `website2`'s domain in my `website1` frontend? I'll still be able to easily create a valid token for `website2`. Just use their domain.

OAuth2 usually prevents it with callbacks allowlists.
- https://auth0.com/docs/login/redirect-users-after-login#redirect-users-to-callback-urls-on-the-allowlist
- https://datatracker.ietf.org/doc/html/rfc6749#section-10.15

**Comment by bytesbay** [comment]
@kaaboaye actually nothing will stop to do it , but the user always see what he is signing

**Comment by kaaboaye** [comment]
Relying on users paying attention to what they are doing is not the best idea for security.

**Comment by gregorym** [comment]
@kaaboaye Just curious, how are you doing auth?

**Comment by kaaboaye** [comment]
OAuth2.

In one project we have auth0 and in another custom auth0 like service. But in general when using external authorization authorities like Google or Facebook OAuth2 a golden standard. It’s well designed, documented and battle tested.

**Comment by john--** [comment]
@kaaboaye How are you doing proof of ownership of a web3 wallet in the oauth flow?

**Comment by kaaboaye** [comment]
We’re using only password and google authentication at the moment.

**Comment by AntMarras** [comment]
any update on this?

**Comment by kaaboaye** [comment]
1. Server will generate a challange 
2. Client will sign the challenge 
3. Client will send the challenge back with signature and all required session information 
4. Server will check if challenge is legitimate, created by authorized server
5. Server will check challenge signature
6. Server will generate a bearer token for the client containing userId, scopes etc

notes
- challenge can be a random string signed with cryptographically secure hmac algorithm which means that server will most likely be sending challenge and serverSignature which client will be sending back with clientSignature
- As long as there we are certain that only this one user could generate given clientSignature there should be no need to compute signatures of userId etc
- Bearer token will most likely be just a JWT token

**Comment by bytesbay** [comment]
@kaaboaye @AntMarras Added domain option in new version

**Comment by kaaboaye** [comment]
Ok, but what stops me from providing another, not mine domain on client side?

**Comment by bytesbay** [comment]
@kaaboaye Nothing. For now all the responsibility is on user's shoulders. We can only wait for EIP-4361 to be implemented in wallets, so the wallets will prevent this vulnerability.
